### ISSUE TITLE
11장 파일이 안열리내요

### ISSUE THREAD

**Issue by manofking** [youngwoos/Doit_Python#1]

**Comment by youngwoos** [comment]
어떤 파일이 어떻게 안열리는지 구체적으로 말씀해주세요?

궁금한 사항이 있으시면 아래 데이터 분석 커뮤니티에 질문을 올려주세요.
보다 빨리 답변을 받아보실 수 있습니다.

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity/

**Comment by manofking** [comment]
> 어떤 파일이 어떻게 안열리는지 구체적으로 말씀해주세요?
> 
> 궁금한 사항이 있으시면 아래 데이터 분석 커뮤니티에 질문을 올려주세요. 보다 빨리 답변을 받아보실 수 있습니다.
> 
> 데이터 분석 커뮤니티 https://www.facebook.com/groups/datacommunity/

**Comment by manofking** [comment]
Notebook폴더안의 11.ipynb파일요. ^^

**Comment by youngwoos** [comment]
11.ipynb는 용량이 커서 깃허브에는 출력되지 않습니다. 파일을 다운로드 받아 주피터랩에서 열어보시겠어요?

**Comment by manofking** [comment]
> 11.ipynb는 용량이 커서 깃허브에는 출력되지 않습니다. 파일을 다운로드 받아 주피터랩에서 열어보시겠어요?

이런 에거가 뜨내요..
![image](https://user-images.githubusercontent.com/60641939/186554937-ef212b17-903d-4967-ae01-1585ea4e2783.png)


파일용량도 문제있내요.
![image](https://user-images.githubusercontent.com/60641939/186554893-fa44f387-8f58-4623-91f4-489b5ccf2e5b.png)

**Comment by youngwoos** [comment]
파일을 다시 다운로드 받아보시겠어요? 노트북 파일을 클릭해 진입한 다음 'Download' 아이콘을 클릭하시면 됩니다. 11.ipynb 파일의 용량은 122MB입니다.

**Comment by normalStarch** [comment]
open 함수에서 파일경로를 절대경로로 해보세요
